pluginManagement {
    repositories {
        // ─── میرورهای ایرانی ───
        maven { url = uri("https://maven.myket.ir") }
        //maven { url = uri("https://maven.devneeds.ir") }
        //maven { url = uri("https://gradle.iranrepo.ir") }
        //maven { url = uri("https://gradle.jamko.ir") }
        //maven { url = uri("https://en-mirror.ir") }
        //maven { url = uri("https://archive.ito.gov.ir/gradle/maven-plugin/") }
        // ─── میرورهای چین ───
        //maven { url = uri("https://maven.aliyun.com/repository/gradle-plugin") }
        //maven { url = uri("https://maven.aliyun.com/repository/google") }
        // ─── منابع رسمی ───
        //google()
        //mavenCentral()
        //gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {

            maven { url = uri("https://maven.myket.ir") }
            //maven { url = uri("https://maven.devneeds.ir") }
            //maven { url = uri("https://gradle.iranrepo.ir") }
            //maven { url = uri("https://gradle.jamko.ir") }
            //maven { url = uri("https://en-mirror.ir") }
            //maven { url = uri("https://archive.ito.gov.ir/gradle/maven-plugin/") }
            //maven { url = uri("https://maven.aliyun.com/repository/public") }
            //maven { url = uri("https://maven.aliyun.com/repository/central") }
            //maven { url = uri("https://maven.aliyun.com/repository/google") }
            google()
            mavenCentral()
            maven { url = uri("https://jitpack.io")}



    }
}
rootProject.name = "tinixmusic2"
include ':app'
